version: "3.9"
services:

  www:
    build:
      context: .
      target: dev
    container_name: www.dispatchlive.co.za
    entrypoint: npm run dev
    environment:
      PORT: "3001"
    ports:
      - 3001:3001
    volumes:
      - ./src:/app/src:ro

  redis:
    image: "redis:alpine"
    container_name: redis.dispatchlive.co.za
